import { defineAgent } from "@platform/sdk";
import { z } from "zod";

/**
 * Generated by agentd (langgraph adapter). Original entry: src/graph.ts
 * Customize input/output schemas after first deploy if needed.
 */
export default defineAgent({
  name: "langgraph-minimal",
  description: "LangGraph agent (imported from src/graph.ts)",
  input: z.object({ message: z.string() }).passthrough(),
  output: z.object({ reply: z.string(), result: z.unknown().optional() }).passthrough(),
  distribute: ["http", "mcp", "cli", "playground"],
  handler: async (input, ctx) => {
  const mod = await import("../src/graph.ts");
  const graph = mod["graph"];
  if (!graph?.invoke) throw new Error("LangGraph export must expose .invoke()");
  const payload = typeof input.message === "string" ? input : { message: JSON.stringify(input) };
  const result = await graph.invoke({
    messages: [{ role: "user", content: payload.message }],
  });
  const messages = result?.messages ?? [];
  const last = messages[messages.length - 1];
  const text = typeof last?.content === "string" ? last.content : JSON.stringify(result);
  return { reply: text, result };
  },
});
